<hgroup>
	<h1>
		TJonesy
	</h1>
	<h2>
		bigfootjonesy@gmail.com
	</h2>
</hgroup>
<img src="http://www.gravatar.com/avatar/<?php echo md5( strtolower( trim( "MyEmailAddress@example.com " ) ) ); ?>" />
<nav>
	<ol>
		<li>
			Portfolio
		</li>
		<li>
			Account
		</li>
	</ol>
</nav>
